### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by dzobbe** [singlestore-labs/python-wasi#5]
When running the ./run.sh script I am getting this error.

implicit declaration of function 'accept' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
ctx->result = accept(s->sock_fd, addr, paddrlen);
                  ^
./Modules/socketmodule.c:2819:19: note: did you mean 'access'?
/opt/wasi-sdk/share/wasi-sysroot/include/unistd.h:118:5: note: 'access' declared here
int access(const char *, int);
    ^

**Comment by kesmit13** [comment]
WASI SDK v15 is needed for this change. I updated the Dockerfile to use the latest WASI SDK.
