### ISSUE TITLE
Coordination across the Python in WebAssembly ecosystem

### ISSUE THREAD

**Issue by brettcannon** [singlestore-labs/python-wasi#8]
Two questions and a request.

Question one: do you know about https://discuss.python.org/c/webassembly/28 ? It's where some announcements and discussions happen around Python and WebAssembly.

Question two: Is anyone from Singlestore Labs looking to come to [PyCon US this year](https://us.pycon.org/2023/)? There may be a WebAssembly summit on Thursday, April 20 for a select number of people (space will be limited).

The request: please feel free to make suggestions upstream to improve how WASI is built, packaged, etc.! I want to get WASI to [tier 2 support for CPython](https://peps.python.org/pep-0011/#tier-2), and part of that will be creating WASI builds as part of releases. Trying to make sure those work as best as possible for the community would be great, so help would be appreciated. Discussions around that can happen at discuss.python.org or on a GitHub issue at https://github.com/python/cpython .

(I believe your team already knows about the [#Python channel on the WebAssembly Discord](https://discord.com/channels/453584038356058112/915046161126137856).)

**Comment by kesmit13** [comment]
@brettcannon I wasn't aware of that Python discussion board on webassembly. It looks like some interesting things going on there. I'll definitely be reading over it.

As far as PyCon goes, I am unsure at the moment. I had an unrelated talk not make the cut which would have had me there. However, knowing that there may be a summit specifically on Wasm would definitely be a good reason to be there. I'll have to look into it.

As far as improving Wasi builds and packaging, we'll be investigating these issues closely in the near future for our own projects. We can bring up any issues we see in the forum or discord.

**Comment by brettcannon** [comment]
> However, knowing that there may be a summit specifically on Wasm would definitely be a good reason to be there. I'll have to look into it.

I'm planning it, so it's happening, but that about as much as we have planned right now. 😅 The room will be limited to 20 people, but I expect we would get you on the list if you chose to come. Any public planning and announcements will happen on discuss.python.org.
